### ISSUE TITLE
typing in logs

### ISSUE THREAD

**Issue by jeff092111** [EthanVieira/rs-clicker#77]
when ever you type it normally does the function of adding the letter twice

**Comment by CurtisGreen** [comment]
What browser are you using? (Chrome, Firefox, safari, etc)

**Comment by EthanVieira** [comment]
I noticed that keys often get duplicated when pressing multiple different keys at the same time. It happens frequently in both Chrome and Firefox. Investigating it now

**Comment by EthanVieira** [comment]
Seems to be a Phaser issue. Try pressing "asdf" at the same time here: https://phaser.io/examples/v3/view/input/keyboard/text-entry.

Put in a hack to keep track of recently used letters. Duplicating letters by holding a key down is a bit slower, but it is necessary to fix this. PR is here: https://github.com/EthanVieira/rs-clicker/pull/78
